#server

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: server
        image: alejo88/devops-integration
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  labels:
    env: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    env: dev